import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [shopName, setShopName] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={() => console.log("送信")}>
          <label>
            shop name:
            <input
              type="text"
              value={shopName}
              onChange={(event) => setShopName(event.target.value)}
            />
          </label>
        </form>
      </main>
    </div>
  );
};

export default Home;
