import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useCallback, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();
  const [shopName, setShopName] = useState("");

  const transitionToShopPage = useCallback(
    (event: React.FormEvent<HTMLFormElement>) => {
      event.preventDefault();
      router.push(`/${shopName}`);
    },
    [router, shopName]
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={transitionToShopPage}>
          <label>
            shop name:
            <input
              type="text"
              value={shopName}
              onChange={(event) => setShopName(event.target.value)}
            />
          </label>
        </form>
      </main>
    </div>
  );
};

export default Home;
