import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { SHOPS } from "../data/shops";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        shop name:
        <select
          onChange={(event) => router.push(`shops/${event.target.value}`)}
          defaultValue=""
        >
          <option value="">Select shop</option>
          {SHOPS.map(({ name }) => (
            <option key={name} value={name}>
              {name}
            </option>
          ))}
        </select>
      </main>
    </div>
  );
};

export default Home;
